Models/AudioData.cs
using Newtonsoft.Json;

namespace ProjectBackend.Models;

public class AudioData
{
    [JsonProperty("id")]
    public long Id { get; set; }

    [JsonProperty("name")]
    public string? Name {get; set;}

    [JsonProperty("file_path")]
    public string? FilePath { get; set; }

    [JsonProperty("duration")]
    public long Duration { get; set; }

    [JsonProperty("audio_type")]
    public long AudioType { get; set; }

    [JsonProperty("sync_data")]
    public List<SyncAudioData>? SyncData { get; set; }

    [JsonIgnore]
    public List<WordAssetData>? WordAssetDatas {get; set;}


}

Controllers/AudioDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using ProjectBackend.Models;

namespace ProjectBackend.Controllers
{
    public class AudioDataParamsHolder
    {
        public IFormFile? AudioFile{get; set;}
    }

    [Authorize]
    public class AudioDataController : Controller
    {
        private readonly MvcWordAssetsContext _context;

        public AudioDataController(MvcWordAssetsContext context)
        {
            _context = context;
        }

        // GET: AudioData
        public async Task<IActionResult> Index()
        {
              return _context.AudioData != null ? 
                          View(await _context.AudioData.ToListAsync()) :
                          Problem("Entity set 'MvcWordAssetsContext.AudioData'  is null.");
        }


        [HttpGet]
        public async Task<IActionResult> Index(string searchPattern)
        {
            if (_context.AudioData == null)
            {
                return Problem("Entity set 'AudioData'  is null.");
            }

            var audioData = from m in _context.AudioData
                         select m;

            if (!String.IsNullOrEmpty(searchPattern))
            {
                Console.WriteLine("WordAsset search " + searchPattern);
                audioData = audioData.Where(s => s.Name!.Contains(searchPattern));
            }


            return View(await audioData.ToListAsync());
        }

        // GET: AudioData/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null || _context.AudioData == null)
            {
                return NotFound();
            }

            var audioData = await _context.AudioData
                .FirstOrDefaultAsync(m => m.Id == id);
            if (audioData == null)
            {
                return NotFound();
            }

            return View(audioData);
        }

        // GET: AudioData/Create
        public IActionResult Create()
        {
            return View();
        }

        // // POST: AudioData/Create
        // // To protect from overposting attacks, enable the specific properties you want to bind to.
        // // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        // [HttpPost]
        // [ValidateAntiForgeryToken]
        // public async Task<IActionResult> Create([Bind("Id,FilePath,Duration,AudioType")] AudioData audioData)
        // {
        //     if (ModelState.IsValid)
        //     {
        //         _context.Add(audioData);
        //         await _context.SaveChangesAsync();
        //         return RedirectToAction(nameof(Index));
        //     }
        //     return View(audioData);
        // }

        // POST: AudioData/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,FilePath,Duration,AudioType")] AudioData audioData, IFormFile audioToUpload)
        {
            if(audioToUpload == null)
            {
                Console.WriteLine("file audio null");
                return Ok();
            }

            //Need To Modify
            var destination = $"{ConfigurationManager.Instance!.GetUnityDataBuildAbsolutePath()}/Audios";
            
            if(!Directory.Exists(destination))
            {
                Directory.CreateDirectory(destination);
            }
            var filePath = Path.Combine(destination, DateTime.Now.ToFileTimeUtc() + Path.GetExtension(audioToUpload.FileName));
            using(var fileStream = System.IO.File.Open(filePath, FileMode.Create))
            {
                await audioToUpload.CopyToAsync(fileStream);

                if (ModelState.IsValid)
                {
                    audioData.FilePath = $"Audios/{Path.GetFileName(filePath)}";
                    _context.Add(audioData);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                return View(audioData);
                
            }

        }

        // GET: AudioData/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null || _context.AudioData == null)
            {
                return NotFound();
            }

            var audioData = await _context.AudioData.FindAsync(id);
            if (audioData == null)
            {
                return NotFound();
            }

            // Need To Modify
            ViewBag.AudioFile = Path.Combine($"{ConfigurationManager.Instance!.GetUnityDataBuildRelativePath()}/Audios", Path.GetFileName(audioData.FilePath!));
            Console.WriteLine("Edit Audio file full path :" + ViewBag.AudioFile);

            return View(audioData);
        }

        // POST: AudioData/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,FilePath,Duration,AudioType")] AudioData audioData, [Bind("AudioFile")] AudioDataParamsHolder audioDataParamsHolder)
        {
            if (id != audioData.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                // Need To Modify
                if(audioDataParamsHolder != null && audioDataParamsHolder.AudioFile != null)
                {
                    var filePath = Path.Combine($"{ConfigurationManager.Instance!.GetUnityDataBuildAbsolutePath()}/Audios", Path.GetFileName(audioData.FilePath!));

                    using(var fileStream = System.IO.File.Open(filePath, FileMode.OpenOrCreate))
                    {
                        await audioDataParamsHolder.AudioFile.CopyToAsync(fileStream);

                        // Maybe cause bug
                    }
                }

                try
                {
                    _context.Update(audioData);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AudioDataExists(audioData.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(audioData);
        }

        // GET: AudioData/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null || _context.AudioData == null)
            {
                return NotFound();
            }

            var audioData = await _context.AudioData
                .FirstOrDefaultAsync(m => m.Id == id);
            if (audioData == null)
            {
                return NotFound();
            }

            return View(audioData);
        }

        // POST: AudioData/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            if (_context.AudioData == null)
            {
                return Problem("Entity set 'MvcWordAssetsContext.AudioData'  is null.");
            }
            var audioData = await _context.AudioData.FindAsync(id);
            if (audioData != null)
            {
                _context.AudioData.Remove(audioData);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AudioDataExists(long id)
        {
          return (_context.AudioData?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/AudioData/Create.cshtml
@model ProjectBackend.Models.AudioData

@{
    ViewData["Title"] = "Create";
    //Layout = "/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>AudioData</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            @* <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="AudioType" class="control-label"></label>
                <input asp-for="AudioType" class="form-control" />
                <span asp-validation-for="AudioType" class="text-danger"></span>
            </div>



            <div class="form-group">
                <span>Select your audio </span>
                <input type="file" id="audioInput" name="audioToUpload" />
                <audio controls id="audioPlayer" style="display:none"></audio>

            </div>

            <br />
            <span> @Html.Raw(ViewBag.Message)</span>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

<script>
    document.getElementById('audioInput').addEventListener('change', function (event) {
        const file = event.target.files[0];
        const audioPlayer = document.getElementById('audioPlayer');

        if (audioPlayer.hasChildNodes()) {
            audioPlayer.removeChild(audioPlayer.firstChild)
        }
        const source = document.createElement('source');

        const objectURL = URL.createObjectURL(file);
        source.src = objectURL;
        source.type = 'audio/mpeg';

        audioPlayer.appendChild(source);
        audioPlayer.load();
        audioPlayer.style.display = 'block';
    });

</script>

Views/AudioData/Delete.cshtml
@model ProjectBackend.Models.AudioData

@{
    ViewData["Title"] = "Delete";
    //Layout = "/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AudioData</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FilePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FilePath)
        </dd>
        @* <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd> *@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AudioType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AudioType)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/AudioData/Details.cshtml
@model ProjectBackend.Models.AudioData

@{
    ViewData["Title"] = "Details";
    //Layout = "/Views/Shared/_AdminLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>AudioData</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FilePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FilePath)
        </dd>
        @* <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd> *@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AudioType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AudioType)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/AudioData/Edit.cshtml
@model ProjectBackend.Models.AudioData

@{
    ViewData["Title"] = "Edit";
    //Layout = "/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit</h1>

<h4>AudioData</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <input type="file" name="audioFile" id="audioInput" />
                <video id="audioPreview" controls="" autoplay="" name="media">
                    <source src="@ViewBag.AudioFile" type="audio/mpeg" >
                </video>
            </div>
            <div class="form-group">
                <label asp-for="FilePath" class="control-label"></label>
                <input asp-for="FilePath" class="form-control" />
                <span asp-validation-for="FilePath" class="text-danger"></span>
            </div>
            @* <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="AudioType" class="control-label"></label>
                <input asp-for="AudioType" class="form-control" />
                <span asp-validation-for="AudioType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>

</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}


<script>
    document.getElementById('audioInput').addEventListener('change', function (event) {
        const file = event.target.files[0];
        const audioPlayer = document.getElementById('audioPreview');

        if (audioPlayer.hasChildNodes()) {
            audioPlayer.removeChild(audioPlayer.firstChild)
        }
        const source = document.createElement('source');

        const objectURL = URL.createObjectURL(file);
        source.src = objectURL;
        source.type = 'audio/mpeg';

        audioPlayer.appendChild(source);
        audioPlayer.load();
        audioPlayer.style.display = 'block';
    });

</script>

Views/AudioData/Index.cshtml
@model IEnumerable<ProjectBackend.Models.AudioData>

@{
    ViewData["Title"] = "Index";
    //Layout = "/Views/Shared/_AdminLayout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="AudioData" asp-action="Index" method="get">
    <p>
        Word: <input type="text" name="searchPattern" />
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FilePath)
            </th>
            @* <th>
                @Html.DisplayNameFor(model => model.Duration)
            </th> *@
            <th>
                @Html.DisplayNameFor(model => model.AudioType)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FilePath)
            </td>
            @* <td>
                @Html.DisplayFor(modelItem => item.Duration)
            </td> *@
            <td>
                @Html.DisplayFor(modelItem => item.AudioType)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>