Models/WordAssetData.cs
using Newtonsoft.Json;

namespace ProjectBackend.Models;

public class WordAssetData
{
    [JsonProperty("word_id")]
    public long ID { get; set; }

    [JsonProperty("text")]
    public string? Text { get; set; }

    [JsonProperty("level_age")]
    public int LevelAge {get; set;}

    [JsonProperty("topic")]
    public long TopicDataID {get; set;}
    [JsonIgnore]
    public virtual TopicData? TopicData {get; set;}

    [JsonProperty("path_asset")]
    public string? PathAsset { get; set; }

    [JsonProperty("sentence_type")]
    public long SentenceType { get; set; }

    [JsonProperty("image")]
    public List<ImageData>? Images { get; set; }

    [JsonProperty("video")]
    public List<VideoData>? Videos { get; set; }

    [JsonProperty("audio")]
    public List<AudioData>? Audios { get; set; }

    [JsonProperty("animations")]
    public List<AnimationData>? Animations { get; set; }

    [JsonProperty("model_3d")]
    public List<Model3DData>? Model3Ds { get; set; }

    [JsonProperty("filter_word")]
    public List<WordAssetData>? FilterWords { get; set; }

    [JsonProperty("games")]
    public List<GameLessonData>? Games { get; set; }

    [JsonProperty("stories")]
    public List<StoryData>? Stories {get; set;}

    [JsonProperty("version")]
    public long Version {get; set;}
}

Controllers/WordAssetDataController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Diagnostics;
using System.IO.Compression;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.StaticFiles;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using ProjectBackend.Models;

namespace ProjectBackend.Controllers
{
    public class WordAssetDataCreateParamsHolder
    {

        public bool IsNeedToBuildAssetBundle { get; set; }
        public IFormFile? FlashCardImage { get; set; }
    }

    [Authorize]
    public class WordAssetDataController : Controller
    {
        private readonly MvcWordAssetsContext _context;

        public WordAssetDataController(MvcWordAssetsContext context)
        {
            _context = context;
        }

        // GET: WordAssetData
        public async Task<IActionResult> Index()
        {
            return _context.WordAssetData != null ?
                        View(await _context.WordAssetData.ToListAsync()) :
                        Problem("Entity set 'MvcWordAssetsContext.WordAssetData'  is null.");
        }

        [HttpGet]
        public async Task<IActionResult> Index(string searchPattern)
        {
            if (_context.WordAssetData == null)
            {
                return Problem("Entity set 'WordAssetData'  is null.");
            }

            var wordAssets = from m in _context.WordAssetData
                             select m;

            if (!String.IsNullOrEmpty(searchPattern))
            {
                Console.WriteLine("WordAsset search " + searchPattern);
                wordAssets = wordAssets.Where(s => s.Text!.Contains(searchPattern));
            }

            return View(await wordAssets.ToListAsync());
        }



        // GET: WordAssetData/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null || _context.WordAssetData == null)
            {
                return NotFound();
            }

            var wordAssetData = await _context.WordAssetData
                .FirstOrDefaultAsync(m => m.ID == id);
            if (wordAssetData == null)
            {
                return NotFound();
            }

            return View(wordAssetData);
        }

        // GET: WordAssetData/Create
        public IActionResult Create()
        {
            Console.WriteLine(ConfigurationManager.Instance!.Configuration!["Something"]);
            ViewBag.TopicDataID = new SelectList(_context.TopicData, "Id", "Id");
            return View();
        }

        // POST: WordAssetData/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Text,PathAsset,SentenceType, TopicDataID, LevelAge")] WordAssetData wordAssetData, [Bind("IsNeedToBuildAssetBundle, FlashCardImage")] WordAssetDataCreateParamsHolder createStructData)
        {
            if (ModelState.IsValid)
            {
                // Need To Modify
                var doneFile1 = false;
                var doneFile2 = false;

                _context.Add(wordAssetData);
                await _context.SaveChangesAsync();

                ViewBag.TopicDataID = new SelectList(_context.TopicData, "Id", "Id", wordAssetData.TopicDataID);

                Console.WriteLine($"Created wordasset ID: {wordAssetData.ID}");

                var destinationDir = $"{ConfigurationManager.Instance!.GetUnityDataBuildAbsolutePath()}/WordAssets/{wordAssetData.ID}";
                if (!Directory.Exists(destinationDir))
                {
                    Console.WriteLine("Created Word Asset Dir");
                    Directory.CreateDirectory(destinationDir);
                }

                if (createStructData != null && createStructData.FlashCardImage != null)
                {
                    var imageDestinationDir = Path.Combine(destinationDir, "Images");
                    if (!Directory.Exists(imageDestinationDir))
                    {
                        Directory.CreateDirectory(imageDestinationDir);
                    }
                    var flashCardFilePath = Path.Combine(imageDestinationDir, $"flashcard_word_id_{wordAssetData.ID}{Path.GetExtension(createStructData.FlashCardImage.FileName)}");

                    var imageTempDir = $"{ConfigurationManager.Instance!.GetUnityDataBuildAbsolutePath()}/Flashcards";

                    Console.WriteLine("Create image TempDir" + imageTempDir);

                    if (!Directory.Exists(imageTempDir))
                    {
                        Directory.CreateDirectory(imageTempDir);
                    }

                    var imageTempDestination = Path.Combine(imageTempDir, Path.GetFileName(flashCardFilePath));

                    using (var fileTempStream = System.IO.File.Open(imageTempDestination, FileMode.OpenOrCreate))
                    {
                        await createStructData.FlashCardImage.CopyToAsync(fileTempStream);
                        doneFile1 = true;
                    }

                    using (var fileStream = System.IO.File.Open(flashCardFilePath, FileMode.OpenOrCreate))
                    {
                        await createStructData.FlashCardImage.CopyToAsync(fileStream);

                        if (wordAssetData.Images == null)
                        {
                            wordAssetData.Images = new();
                        }

                        var imageData = new ImageData
                        {
                            FilePath = $"{Path.GetFileName(flashCardFilePath)}",
                            Link = $"Flashcards/{Path.GetFileName(flashCardFilePath)}",
                            Name = $"{wordAssetData.Text}_{wordAssetData.ID}_FlashCard",
                            ImageType = (long)AssetDataType.ImageType.Flashcard
                        };
                        _context.Add(imageData);
                        wordAssetData.Images.Add(imageData);
                        await _context.SaveChangesAsync();
                        doneFile2 = true;
                    }
                }
                else
                {
                    doneFile1 = true;
                    doneFile2 = true;
                }

                // _context.Add(wordAssetData);

                while (!(doneFile1 && doneFile2)) ;

                UpdateConfigFile(wordAssetData.ID);

                //Need To Modify
                var endPoint = $"https://localhost:7253/WordAssetData/api/download?fileName={wordAssetData.ID}.unity3d"; ;

                var wordAssetInfoDownload = new WordAssets
                {
                    Id = wordAssetData.ID,
                    Text = wordAssetData.Text,
                    LinkDownLoad = endPoint,
                    DateCreated = DateTime.Now

                };

                _context.Add(wordAssetInfoDownload);

                await _context.SaveChangesAsync();

                Console.WriteLine("IsNeedToBuildAssetBundle "+ createStructData!.IsNeedToBuildAssetBundle);

                if (createStructData!.IsNeedToBuildAssetBundle)
                {
                    Console.WriteLine("Build AssetBundle");

                    //await _context.WordAssetData!.ForEachAsync(x => UpdateConfigFile(x.ID));
                    
                    AssetBuilder.ImportAssetAndBuildAssetBundle();
                }

                return RedirectToAction(nameof(Index));
            }
            return View(wordAssetData);
        }

        // GET: WordAssetData/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null || _context.WordAssetData == null)
            {
                return NotFound();
            }

            //var wordAssetData = await _context.WordAssetData.FindAsync(id);
            var st = _context.WordAssetData
            .Include(x => x.Model3Ds)
            .Include(x => x.Audios)
            .Include(x => x.Images)
            .Include(x => x.Videos)
            .Include(x => x.Games)
                .ThenInclude(y => y.GameData)
            .Include(x => x.Stories);
            var wordAssetData = st.FirstOrDefault(m => m.ID == id);
            if (wordAssetData == null)
            {
                return NotFound();
            }

            var flashCard = wordAssetData.Images!.Find(x => x.ImageType == (long)AssetDataType.ImageType.Flashcard);

            // Need To Modify
            ViewData["Model3DDataID"] = new SelectList(_context.Model3DData, "Id", "Id");
            ViewBag.FlashCardPath = $"{ConfigurationManager.Instance!.GetUnityDataBuildRelativePath()}/{flashCard?.Link}";
            ViewBag.TopicDataID = new SelectList(_context.TopicData, "Id", "Id");

            await Task.Yield();

            return View(wordAssetData);
        }

        // POST: WordAssetData/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("ID,Text,PathAsset,SentenceType, TopicDataID, LevelAge")] WordAssetData wordAssetData)
        {
            if (id != wordAssetData.ID)
            {
                return NotFound();

Views/WordAssetData/Create.cshtml

@model ProjectBackend.Models.WordAssetData

@{
    ViewData["Title"] = "Create";
    //Layout = "/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>WordAssetData</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            @* <div class="form-group">
                <label asp-for="PathAsset" class="control-label"></label>
                <input asp-for="PathAsset" class="form-control" />
                <span asp-validation-for="PathAsset" class="text-danger"></span>
            </div> *@

            <div class="form-group">
                <label asp-for="TopicDataID" class="control-label"></label>
                <select asp-for="TopicDataID" class ="form-control" asp-items="ViewBag.TopicDataID"></select>
            </div>

            <div class="form-group">
                <label asp-for="SentenceType" class="control-label"></label>
                <input asp-for="SentenceType" class="form-control" />
                <span asp-validation-for="SentenceType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LevelAge" class="control-label"></label>
                <input asp-for="LevelAge" class="form-control" />
                <span asp-validation-for="LevelAge" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type='file' onchange="readURL(this);" name= "FlashCardImage"/>
                <img id="imgPrevFlashcard" src="http://placehold.it/180" alt="your image" style="max-width: 180px;"/>
            </div>

            <div class="form-group">
                <label  class="control-label">Build AssetBundle</label>
                <input type="checkbox" value="true" name="IsNeedToBuildAssetBundle" />
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>


</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#imgPrevFlashcard')
                    .attr('src', e.target.result);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

Views/WordAssetData/CreateByFile.cshtml
@model ProjectBackend.Models.WordAssetData

@{
    //Layout = "/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create Word Assets by zip file</h1>

<h4>Model3DData</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="CreateByFile" >
            <span>Select your file </span>
            <input type="file" name="fileToUpload" accept=".zip" />

            <br/>
            <span> @Html.Raw(ViewBag.Message)</span>

            <div class="form-group">
                <input type="submit" value="CreateByFile" class="btn btn-primary" />
            </div>
        </form>

    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/WordAssetData/Delete.cshtml
@model ProjectBackend.Models.WordAssetData

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>WordAssetData</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PathAsset)
        </dt>
        @* <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PathAsset)
        </dd> *@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TopicDataID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TopicDataID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SentenceType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SentenceType)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/WordAssetData/Details.cshtml
@model ProjectBackend.Models.WordAssetData

@{
    ViewData["Title"] = "Details";
    //Layout = "/Views/Shared/_AdminLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>WordAssetData</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
        @* <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PathAsset)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PathAsset)
        </dd> *@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TopicDataID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TopicDataID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SentenceType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SentenceType)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/WordAssetData/Index.cshtml
@model IEnumerable<ProjectBackend.Models.WordAssetData>

@{
    ViewData["Title"] = "Index";
    //Layout = "/Views/Shared/_AdminLayout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="WordAssetData" asp-action="Index" method="get">
    <p>
        Word: <input type="text" name="searchPattern" />
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Text)
            </th>
            @* <th>
                @Html.DisplayNameFor(model => model.PathAsset)
            </th> *@
            <th>
                @Html.DisplayNameFor(model => model.TopicDataID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SentenceType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LevelAge)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Text)
            </td>
            @* <td>
                @Html.DisplayFor(modelItem => item.PathAsset)
            </td> *@
            <td>
                @Html.DisplayFor(modelItem => item.TopicDataID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SentenceType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LevelAge)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>