Models/VideoData.cs

using Newtonsoft.Json;

namespace ProjectBackend.Models;

public partial class VideoData
{
    [JsonProperty("id")]
    public int Id { get; set; }

    [JsonProperty("name")]
    public string? Name {get; set;}

    [JsonProperty("link")]
    public string? Link { get; set; }

    [JsonProperty("file_path")]
    public string? FilePath { get; set; }

    [JsonProperty("duration")]
    public int Duration { get; set; }

    [JsonProperty("video_type")]
    public int VideoType { get; set; }

    [JsonIgnore]
    public List<WordAssetData>? WordAssetDatas{get; set;}
}

Controllers/VideoDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic;
using ProjectBackend.Models;

namespace ProjectBackend.Controllers
{
    public class VideoDataParamsHolder
    {
        public IFormFile? VideoFile { get; set; }
    }

    [Authorize]
    public class VideoDataController : Controller
    {
        private readonly MvcWordAssetsContext _context;

        public VideoDataController(MvcWordAssetsContext context)
        {
            _context = context;
        }

        // GET: VideoData
        public async Task<IActionResult> Index()
        {
            return _context.VideoData != null ?
                        View(await _context.VideoData.ToListAsync()) :
                        Problem("Entity set 'MvcWordAssetsContext.VideoData'  is null.");
        }


        [HttpGet]
        public async Task<IActionResult> Index(string searchPattern)
        {
            if (_context.VideoData == null)
            {
                return Problem("Entity set 'VideoData'  is null.");
            }

            var videoData = from m in _context.VideoData
                         select m;

            if (!String.IsNullOrEmpty(searchPattern))
            {
                Console.WriteLine("VideoData search " + searchPattern);
                videoData = videoData.Where(s => s.Name!.Contains(searchPattern));
            }

            return View(await videoData.ToListAsync());
        }

        // GET: VideoData/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.VideoData == null)
            {
                return NotFound();
            }

            var videoData = await _context.VideoData
                .FirstOrDefaultAsync(m => m.Id == id);
            if (videoData == null)
            {
                return NotFound();
            }

            return View(videoData);
        }

        // GET: VideoData/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: VideoData/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name, Link,FilePath,Duration,VideoType")] VideoData videoData, [Bind("VideoFile")] VideoDataParamsHolder videoCreateDataHolder)
        {
            //Need To Modify
            var destinationDir = $"{ConfigurationManager.Instance!.GetUnityDataBuildAbsolutePath()}/Videos";
            if (!Directory.Exists(destinationDir))
            {
                Directory.CreateDirectory(destinationDir);
            }
            var filePath = Path.Combine(destinationDir, DateTime.UtcNow.ToFileTimeUtc() + Path.GetExtension(videoCreateDataHolder.VideoFile!.FileName));
            
            using (var fileStream = System.IO.File.Open(filePath, FileMode.OpenOrCreate))
            {

                await videoCreateDataHolder.VideoFile.CopyToAsync(fileStream);
                videoData.FilePath = Path.GetFileName(filePath);
                videoData.Link = "video/" + Path.GetFileName(filePath);

                if (ModelState.IsValid)
                {
                    _context.Add(videoData);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                return View(videoData);
            }
        }

        // GET: VideoData/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.VideoData == null)
            {
                return NotFound();
            }

            var videoData = await _context.VideoData.FindAsync(id);
            if (videoData == null)
            {
                return NotFound();
            }

            ViewBag.VideoFile = Path.Combine($"{ConfigurationManager.Instance!.GetUnityDataBuildRelativePath()}/Videos", videoData.FilePath!);
            
            return View(videoData);
        }

        // POST: VideoData/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Link,FilePath,Duration,VideoType")] VideoData videoData, [Bind("VideoFile")] VideoDataParamsHolder videoDataParamsHolder)
        {
            if (id != videoData.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                //Need To Modify
                if(videoDataParamsHolder != null && videoDataParamsHolder.VideoFile != null)
                {
                    var filePath = Path.Combine($"{ConfigurationManager.Instance!.GetUnityDataBuildAbsolutePath()}/Videos", Path.GetFileName(videoData.FilePath!));
                    using(var fileStream = System.IO.File.Open(filePath, FileMode.OpenOrCreate))
                    {
                        await videoDataParamsHolder.VideoFile.CopyToAsync(fileStream);
                    }
                }

                try
                {
                    _context.Update(videoData);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VideoDataExists(videoData.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(videoData);
        }

        // GET: VideoData/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.VideoData == null)
            {
                return NotFound();
            }

            var videoData = await _context.VideoData
                .FirstOrDefaultAsync(m => m.Id == id);
            if (videoData == null)
            {
                return NotFound();
            }

            return View(videoData);
        }

        // POST: VideoData/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.VideoData == null)
            {
                return Problem("Entity set 'MvcWordAssetsContext.VideoData'  is null.");
            }
            var videoData = await _context.VideoData.FindAsync(id);
            if (videoData != null)
            {
                _context.VideoData.Remove(videoData);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VideoDataExists(int id)
        {
            return (_context.VideoData?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/VideoData/Create.cshtml

@model ProjectBackend.Models.VideoData

@{
    ViewData["Title"] = "Create";
    //Layout = "/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>VideoData</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <input type="file" name="VideoFile" id="videoInput" />
                <video id="videoPreview" controls="" autoplay="" name="media">

                </video>
            </div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="VideoType" class="control-label"></label>
                <input asp-for="VideoType" class="form-control" />
                <span asp-validation-for="VideoType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}


<script>
    document.getElementById('videoInput').addEventListener('change', function (event) {
        const file = event.target.files[0];
        const videoPlayer = document.getElementById('videoPreview');

        if (videoPlayer.hasChildNodes()) {
            videoPlayer.removeChild(videoPlayer.firstChild)
        }
        const source = document.createElement('source');

        const objectURL = URL.createObjectURL(file);
        source.src = objectURL;
        source.type = 'video/mp4';

        videoPlayer.appendChild(source);
        videoPlayer.load();
        videoPlayer.style.display = 'block';
    });

</script>

Views/VideoData/Delete.cshtml
@model ProjectBackend.Models.VideoData

@{
    ViewData["Title"] = "Delete";
    //Layout = "/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>VideoData</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Link)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Link)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FilePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FilePath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VideoType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VideoType)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/VideoData/Details.cshtml
@model ProjectBackend.Models.VideoData

@{
    ViewData["Title"] = "Details";
    //Layout = "/Views/Shared/_AdminLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>VideoData</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Link)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Link)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FilePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FilePath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VideoType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VideoType)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/VideoData/Edit.cshtml
@model ProjectBackend.Models.VideoData

@{
    ViewData["Title"] = "Edit";
    //Layout = "/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit</h1>

<h4>VideoData</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <input type="file" name="VideoFile" id="videoInput" />
                <video id="videoPreview" controls="" autoplay="" name="media">
                    <source src="@ViewBag.VideoFile" type="video/mp4" >
                </video>
            </div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="VideoType" class="control-label"></label>
                <input asp-for="VideoType" class="form-control" />
                <span asp-validation-for="VideoType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}


<script>
    document.getElementById('videoInput').addEventListener('change', function (event) {
        const file = event.target.files[0];
        const videoPlayer = document.getElementById('videoPreview');

        if (videoPlayer.hasChildNodes()) {
            videoPlayer.removeChild(videoPlayer.firstChild)
        }
        const source = document.createElement('source');

        const objectURL = URL.createObjectURL(file);
        source.src = objectURL;
        source.type = 'video/mp4';

        videoPlayer.appendChild(source);
        videoPlayer.load();
        videoPlayer.style.display = 'block';
    });

</script>

Views/VideoData/Index.cshtml
@model IEnumerable<ProjectBackend.Models.VideoData>

@{
    ViewData["Title"] = "Index";
    //Layout = "/Views/Shared/_AdminLayout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="VideoData" asp-action="Index" method="get">
    <p>
        Audio Name: <input type="text" name="searchPattern" />
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Link)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FilePath)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Duration)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VideoType)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Link)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FilePath)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Duration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VideoType)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>