Models/Model3DData.cs

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Newtonsoft.Json;

namespace ProjectBackend.Models ;

public class Model3DData
{
    [JsonProperty("id")]
    public long Id { get; set; }

    [JsonProperty("name")]
    public string? Name { get; set; }

    [JsonProperty("link_download")]
    public string? LinkDownload { get; set; }

    [JsonProperty("location")]
    public string? Location {get; set;}

    [JsonProperty("name_asset")]
    public string? NameAsset {get; set;}

    [JsonProperty("file_type")]
    public string? FileType { get; set; }

    [JsonProperty("scale_factor")]
    public float ScaleFactor {get; set;}

    [JsonProperty("behavior")]
    public List<Mode3DBehaviorData>? Behavior { get; set; }

    [JsonProperty("word_description")]
    public long WordDescription {get; set;}

    [JsonIgnore]
    public ICollection<WordAssetData>? WordAssetDatas {get; set;}


    
}

Controllers/Model3DDataController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.StaticFiles;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NuGet.Protocol;
using NuGet.Protocol.Core.Types;
using ProjectBackend.Models;

namespace ProjectBackend.Controllers
{

    public class Model3DDataParamsHolder
    {
        public IFormFile? File3DModel { get; set; }
    }

    [Authorize]
    public class Model3DDataController : Controller
    {
        private static string ApiKey = "AIzaSyCZBeMCx5PYzlkZepR74hOHj-FbXZlgVbQ";
        private static string Bucket = "arenkid-projectbe.appspot.com";
        private static string AuthEmail = "kingsoulz4d@gmail.com";
        private static string AuthPassword = "55444664";

        private readonly MvcWordAssetsContext _context;

        public Model3DDataController(MvcWordAssetsContext context)
        {
            _context = context;
        }

        // GET: Model3DData
        public async Task<IActionResult> Index()
        {
            return _context.Model3DData != null ?
                        View(await _context.Model3DData.ToListAsync()) :
                        Problem("Entity set 'MvcWordAssetsContext.Model3DData'  is null.");
        }

        [HttpGet]
        public async Task<IActionResult> Index(string searchPattern)
        {
            if (_context.Model3DData == null)
            {
                return Problem("Entity set 'Model3DData'  is null.");
            }

            var model3DData = from m in _context.Model3DData
                              select m;

            if (!String.IsNullOrEmpty(searchPattern))
            {
                Console.WriteLine("VideoData search " + searchPattern);
                model3DData = model3DData.Where(s => s.Name!.Contains(searchPattern));
            }


            return View(await model3DData.ToListAsync());
        }

        // GET: Model3DData/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null || _context.Model3DData == null)
            {
                return NotFound();
            }

            var model3DData = await _context.Model3DData
                .FirstOrDefaultAsync(m => m.Id == id);
            if (model3DData == null)
            {
                return NotFound();
            }

            return View(model3DData);
        }

        // GET: Model3DData/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Model3DData/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,LinkDownload,FileType, ScaleFactor, Location, NameAsset, WordDescription")] Model3DData model3DData, [Bind("File3DModel")] Model3DDataParamsHolder paramsHolder)
        {
            Console.WriteLine("Model valid " + ModelState.IsValid);
            //Console.WriteLine("Model valid " + ModelState.);
            if (ModelState.IsValid)
            {
                bool uploadDone = false;

                //var resultUpload = await UploadHelper.UpLoadFileToFirebaseStorage(fileToUpload, ApiKey, AuthEmail, AuthPassword, Bucket, "something/data");

                var destinationDir = Path.Combine(ConfigurationManager.Instance!.GetUnityDataBuildAbsolutePath(), DataDirectoryNames.Model3DDataDir);

                if (!Directory.Exists(destinationDir))
                {
                    Directory.CreateDirectory(destinationDir);
                }

                var fileToUpload = paramsHolder.File3DModel;

                if (fileToUpload != null)
                {

                    var filePath = Path.Combine(destinationDir, DateTime.Now.ToFileTimeUtc() + Path.GetExtension(fileToUpload.FileName));

                    using (var fileStream = System.IO.File.Open(filePath, FileMode.OpenOrCreate))
                    {
                        await fileToUpload.CopyToAsync(fileStream);
                        uploadDone = true;
                    }

                    while (!uploadDone) ;

                    //Need To Modify
                    var endPoint = $"https://localhost:7253/Model3DData/api/download?fileName={Path.GetFileName(filePath)}";

                    // Console.WriteLine("Upload res: " + resultUpload.ToJToken());
                    // var jsonTokRes = resultUpload.ToJToken();
                    // var val = jsonTokRes.SelectToken("Value");
                    // var linkDownload = val!.Value<string>("message");
                    var linkDownload = endPoint;
                    Console.WriteLine("ModelDDataController Download link: " + linkDownload);

                    model3DData.FileType = Path.GetExtension(fileToUpload.FileName);
                    model3DData.LinkDownload = linkDownload;
                }

                _context.Add(model3DData);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model3DData);
        }

        // GET: Model3DData/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null || _context.Model3DData == null)
            {
                return NotFound();
            }

            var model3DData = _context.Model3DData
            .Include(x => x.Behavior)
            .FirstOrDefault(x => x.Id == id);
            if (model3DData == null)
            {
                return NotFound();
            }

            await Task.Yield();

            return View(model3DData);
        }

        // POST: Model3DData/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Name,LinkDownload,FileType, ScaleFactor, Location, NameAsset, WordDescription")] Model3DData model3DData)
        {
            if (id != model3DData.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(model3DData);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Model3DDataExists(model3DData.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model3DData);
        }

        // GET: Model3DData/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null || _context.Model3DData == null)
            {
                return NotFound();
            }

            var model3DData = await _context.Model3DData
                .FirstOrDefaultAsync(m => m.Id == id);
            if (model3DData == null)
            {
                return NotFound();
            }

            return View(model3DData);
        }

        // POST: Model3DData/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            if (_context.Model3DData == null)
            {
                return Problem("Entity set 'MvcWordAssetsContext.Model3DData'  is null.");
            }
            var model3DData = await _context.Model3DData.FindAsync(id);
            if (model3DData != null)
            {
                _context.Model3DData.Remove(model3DData);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Model3DDataExists(long id)
        {
            return (_context.Model3DData?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        public async Task<IActionResult> AddOrRemoveBehavior(long model3DID, long behaviorID)
        {

            var model3D = _context.Model3DData!
            .Include(x => x.Behavior)
            .Where(x => x.Id == model3DID).Single();

            var behavior = _context.Mode3DBehaviorData!.Where(x => x.Id == behaviorID).Single();

            if (behavior == null)
            {
                return Problem("Behavior not exist");
            }

            var behaviorBelongTo = model3D.Behavior!.Find(x => x.Id == behavior.Id);

            if (!model3D.Behavior!.Any() ||
                 behaviorBelongTo != null)
            {
                model3D.Behavior!.Add(behavior);
            }
            else
            {
                model3D.Behavior.Remove(behaviorBelongTo!);
            }

            await Task.Yield();

            return RedirectToAction(nameof(Edit), new { id = model3DID });
        }


        [HttpPost]
        public async Task<ActionResult> UploadModel3DToCloud(IFormFile fileToUpload)
        {
            await UploadHelper.UpLoadFileToFirebaseStorage(fileToUpload, ApiKey, AuthEmail, AuthPassword, Bucket, "something/data");


Views/Model3DData/Create.cshtml
@model ProjectBackend.Models.Model3DData

@{

    ViewData["Title"] = "Create";
    //Layout = "/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>Model3DData</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ScaleFactor" class="control-label"></label>
                <input asp-for="ScaleFactor" class="form-control" />
                <span asp-validation-for="ScaleFactor" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="NameAsset" class="control-label"></label>
                <input asp-for="NameAsset" class="form-control" />
                <span asp-validation-for="NameAsset" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WordDescription" class="control-label"></label>
                <input asp-for="WordDescription" class="form-control" />
                <span asp-validation-for="WordDescription" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <select asp-for="Location">
                    <option value="AssetBundle">AssetBundle</option>
                    <option value="File">File</option>
                </select>
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            @* <div class="form-group">
            <label asp-for="LinkDownload" class="control-label"></label>
            <input asp-for="LinkDownload" class="form-control" />
            <span asp-validation-for="LinkDownload" class="text-danger"></span>
            </div> *@
            @* <div class="form-group">
            <label asp-for="FileType" class="control-label"></label>
            <input asp-for="FileType" class="form-control" />
            <span asp-validation-for="FileType" class="text-danger"></span>
            </div> *@

            <div class="form-group">
                <span>Select your file </span>
                <input type="file" name="File3DModel" />
            </div>
            
            @* <input type="submit" value="Upload"/> *@

            <br />
            <span> @Html.Raw(ViewBag.Message)</span>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>

        @* <form method="post" enctype="multipart/form-data" asp-controller="Model3DData"
        asp-action="UploadModel3DToCloud">
        <span>Select your file </span>
        <input type="file" name="fileToUpload" />
        <input type="submit" value="Upload"/>

        <br/>
        <span> @Html.Raw(ViewBag.Message)</span>

        </form> *@
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Model3DData/Delete.cshtml
@model ProjectBackend.Models.Model3DData

@{
    ViewData["Title"] = "Delete";
    //Layout = "/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Model3DData</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LinkDownload)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LinkDownload)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FileType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FileType)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Model3DData/Details.cshtml
@model ProjectBackend.Models.Model3DData

@{
    ViewData["Title"] = "Details";
    //Layout = "/Views/Shared/_AdminLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Model3DData</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LinkDownload)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LinkDownload)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FileType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FileType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ScaleFactor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ScaleFactor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WordDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WordDescription)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Model3DData/Edit.cshtml
@model ProjectBackend.Models.Model3DData

@{
    ViewData["Title"] = "Edit";
    //Layout = "/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit</h1>

<h4>Model3DData</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="NameAsset" class="control-label"></label>
                <input asp-for="NameAsset" class="form-control" />
                <span asp-validation-for="NameAsset" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <select asp-for="Location">
                    <option value="AssetBundle">AssetBundle</option>
                    <option value="File">File</option>
                </select>
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="LinkDownload" class="control-label"></label>
                <input asp-for="LinkDownload" class="form-control" />
                <span asp-validation-for="LinkDownload" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FileType" class="control-label"></label>
                <input asp-for="FileType" class="form-control" />
                <span asp-validation-for="FileType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ScaleFactor" class="control-label"></label>
                <input asp-for="ScaleFactor" class="form-control" />
                <span asp-validation-for="ScaleFactor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WordDescription" class="control-label"></label>
                <input asp-for="WordDescription" class="form-control" />
                <span asp-validation-for="WordDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>

    <div class="col-md-4">
        <div class="btn-group">
            <button type="button" class="dropdown-toggle btn btn-info" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="true">
                List Behavior
            </button>
            <div class="dropdown-menu justify-content-center">
                @{

                    if (Model.Behavior != null)
                    {
                        Console.WriteLine("dropdown-menu Audio list " + Model.Behavior!.Count);
                        foreach (var be in Model.Behavior!)
                        {
                            <a asp-controller="Mode3DBehaviorData" asp-action="Edit" asp-route-id="@be.Id"> @be.Name - @be.Id </a>
                            <br>
                        }
                    }
                }
            </div>
        </div>
    </div>



</div>

<!-- Config Behavior region -->
<hr class="sidebar-divider">
<div class="row">
    <div class="col-md-4">
        <h6 class="font-weight-bold">
            Config Behavior
        </h6>
        <form asp-action="AddOrRemoveBehavior">

            <div class="form-group">
                <input type="hidden" name="model3DID" value=@Model.Id />
            </div>

            <div class="form-floating mb-3 form-group">
                <label for="behaviorfloatingInput">Enter Behavior ID</label>
                <input name="behaviorID" class="form-control" id="behaviorfloatingInput">

            </div>

            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </form>
        <div>
            <a asp-controller="Mode3DBehaviorData" asp-action="Create">Add New Behavior</a>
        </div>
    </div>
</div>
<hr class="sidebar-divider">

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Model3DData/Index.cshtml
@model IEnumerable<ProjectBackend.Models.Model3DData>

@{
    ViewData["Title"] = "Index";
    //Layout = "/Views/Shared/_AdminLayout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Model3DData" asp-action="Index" method="get">
    <p>
        Model 3D Name: <input type="text" name="searchPattern" />
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LinkDownload)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FileType)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LinkDownload)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FileType)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>